export const DEFAULT_IMAGE_UPLOAD_MB = 1
export const DEFAULT_IMAGE_UPLOAD_BYTES = DEFAULT_IMAGE_UPLOAD_MB * 1024 * 1024

export const BLOG_HEADER_IMAGE_UPLOAD_MB = 2
export const BLOG_HEADER_IMAGE_UPLOAD_BYTES = BLOG_HEADER_IMAGE_UPLOAD_MB * 1024 * 1024
