project:
  type: website
  output-dir: docs
  resources:
    - /images/
    - /templates/

website:
  title: "a11yhood"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "News"
        href: news.qmd
      - text: "About"
        href: about.qmd
  description: "A repository for sharing accessibility solutions"

  site-url: "https://a11yhood.org"
  repo-url: "https://github.com/a11yhood/a11yhood.github.io"
  repo-actions: [edit, source, issue]
  search:
    location: navbar
    copy-button: true
    show-item-context: true
  page-footer: "Copyright {{<var year>}}, {{<var author>}}"

format:
  html:
    theme:
      - yeti
      - style.scss
    linkcolor: "#3a1c6f;"
    toc: true



