[workspace]
authors = ["tonyfast <tony.fast@uw.edu>"]
channels = ["conda-forge"]
name = "a11yhood.github.io"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks.install-gems]
description = "install ruby gems and github pages dependencies"
cmd = ".pixi/envs/{{ pixi.environment.name }}/bin/gem install github-pages"

[tasks.install-pages]
description = "install ruby gems and github pages dependencies"
cmd = ".pixi/envs/{{ pixi.environment.name }}/bin/bundle install"
depends-on = ["install-gems"]

[tasks.serve]
description = "serve the website locally"
cmd = ".pixi/envs/{{ pixi.environment.name }}/bin/bundle exec jekyll serve --livereload"
depends-on = ["install-gems"]

[tasks.build-jekyll]
description = "build the jekyll website for production"
cmd = ".pixi/envs/{{ pixi.environment.name }}/bin/bundle exec jekyll build"
depends-on = ["install-pages"]

[tasks.build-vite]
description = "build the vite website for production"
cmd = "npx vite build"
depends-on = ["install-node"]
# outputs = ["_site/**/*"]

[tasks.install-node]
description = "install node and npm dependencies"
cmd = "npm install"
inputs = ["package.json"]
outputs = ["package-lock.json"]

[dependencies]
# ruby = ">=3.4.8,<4"
# make = ">=4.4.1,<5"
# c-compiler = ">=1.0.0,<2"
# cxx-compiler = ">=1.0.0,<2"
nodejs = ">=20.0,<21"

# [target.linux-64.dependencies]
# gxx_linux-64 = ">=11.4.0,<12"

# [target.osx-arm64.dependencies]
# gcc = ">=15.2.0,<15.3"
